baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Benjamin Hattemer
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

params:
    description: "I am Benjamin, welcome to my website."
    author: Benjamin Hattemer
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    ShowToc: false
    disableScrollToTop: true
    math: true
    profileMode:
          enabled: true
          title: "Benjamin Hattemer"
          subtitle: "I am a postdoctoral researcher in Economics at the Finnish Centre of Excellence in Tax Systems Research at the University of Helsinki. In December 2025, I received my PhD from the European University Institute, under the supervision of [<u>Thomas Crossley</u>](https://sites.google.com/site/tfcrossley/) and [<u>Alexander Monge-Naranjo.</u>](https://alexandermonge.com/).<br><br> My research focuses on applied environmental and labor economics. I study climate policy, with a particular focus on carbon pricing in cap-and-trade systems and on how physical risks associated with climate change shape labor market outcomes." 
          imageUrl: "picture_hat.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: CV
              url: CV.pdf
            - name: Research
              url: research/

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
